spring:
  application:
    name: aw-spring-v2

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASS}
    url: ${POSTGRES_URL}

  jpa:
    database: postgresql
    show-sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true
#    date-format: yyyy-MM-dd

#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          introspection-uri: //localhost:8080/oauth/check_token
#          client-id: ${CLIENT_ID}
#          client-secret: ${CLIENT_SECRET}