spring:
  application:
    name: aw-spring-v2

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASS}
    url: ${POSTGRES_URL}

  jpa:
    database: postgresql
    show-sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true
#    date-format: yyyy-MM-dd

#RESOURCE SERVER CONFIG TO READ JWK RSA PUBLIC KEYS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/
#          jwk-set-uri: http://localhost:8080/oauth2/jwks
